build_pdf:
    image: aergus/latex
    before_script:
        - apt-get update -y
        - apt-get install -y pandoc
    script:
        - make
    artifacts:
        paths:
            - Book.pdf
    only:
        - master