build_pdf:
    image: aergus/latex
    before_script:
        - apt-get update -y
        - apt-get install -y pandoc
    script:
        - make pseudocode_color
    artifacts:
        paths:
            - Book_pseudocode_colored.pdf
    only:
        - master
