blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/2DGD-F0TH/2DGD_F0TH/discussions
    about: If you want to start a long-form discussion on GitHub, you can do so here.
  - name: Itch.io Boards
    url: https://therealpenaz91.itch.io/2dgd-f0th/community
    about: If you want to start a long-form discussion on Itch.io, you can do so here.
