@startuml
class Object{
    + input();
    + update(dt);
    + draw();
    + collide();
}

class VisibleObject{
    + draw();
}

class InvisibleObject{
    + draw();
}

class CollidableObject{
    + collide();
}

class NonCollidableObject{
    + collide();
}

class MovableObject{
    +update();
}

class ImmovableObject{
    +update();
}

class Building{}

VisibleObject -up-|> Object
InvisibleObject -up-|> Object
CollidableObject -up-|> Object
NonCollidableObject -up-|> Object
MovableObject -up-|> Object
ImmovableObject -up-|> Object
Building -up-|> ImmovableObject
Building -up-|> VisibleObject
Building -up-|> CollidableObject
PlayableCharacter -up-|> MovableObject
PlayableCharacter -up-|> CollidableObject
PlayableCharacter -up-|> VisibleObject
@enduml
