@startuml
class Object{
    + input();
    + update(dt);
    + draw();
    + collide();
}

class VisibleObject{
    + draw();
}

class InvisibleObject{
    + draw();
}

class CollidableObject{
    + collide();
}

class NonCollidableObject{
    + collide();
}

class MovableObject{
    +update();
}

class ImmovableObject{
    +update();
}

class Building{}

VisibleObject --|> Object
InvisibleObject --|> Object
CollidableObject --|> Object
NonCollidableObject --|> Object
MovableObject --|> Object
ImmovableObject --|> Object
Building --|> ImmovableObject
Building --|> VisibleObject
Building --|> CollidableObject
PlayableCharacter --|> MovableObject
PlayableCharacter --|> CollidableObject
PlayableCharacter --|> VisibleObject
@enduml
