@startuml
start
:a=input();
if (a == 0) then (yes)
    :b = "zero";
else (no)
    if (a % 2 == 0) then (yes)
        :b = "even";
    else (no)
        :b = "odd";
    endif
endif
:return b;
stop
@enduml
