@startuml
class Client{
    + adaptor: Adaptor
    + doStuff()
}

interface Target{
    + compatibleMethod()
}

class Adaptor{
    + compatibleMethod()
}

note right of Adaptor
    The adapter subclasses
    the adaptee and realizes
    the target interface
end note

class Adaptee{
    + incompatibleMethod()
}

Client -down-> Target
Adaptor .up.|> Target
Adaptor -up-|> Adaptee
@enduml
