@startuml
abstract class DecoratedObject{
    +void doStuff()
}

class Concrete_DecoratedObject{
    +void doStuff()
}

abstract class Decorator{
    -DecoratedObject component
    +void doStuff()
}

class Concrete_Decorator{
    +void doStuff()
}

Decorator -up-|> DecoratedObject
Concrete_DecoratedObject -up-|> DecoratedObject
Concrete_Decorator -up-|> Decorator
Decorator o-- DecoratedObject
@enduml
