@startuml
class Client{
    + adaptor: Target
    + doStuff()
}

interface Target{
    + compatibleMethod()
}

class Adaptor{
    + adaptee: Adaptee
    + compatibleMethod()
}

note right of Adaptor
    The adapter "wraps"
    the adaptee
end note

class Adaptee{
    + incompatibleMethod()
}

Client -left-> Target
Adaptor .up.|> Target
Adaptor -up-> Adaptee
@enduml
