@startuml
interface Prototype{
    + clone()
}

class ConcretePrototype{
    + clone()
}

class Client{
    + doStuff()
}

Client .right.> Prototype : <<import>>
ConcretePrototype .up.|> Prototype

note left of Client
    calls "prototype.clone()"
end note

note left of ConcretePrototype
    the clone() method returns
    a copy of the class
end note
@enduml
