@startuml

class Sender{
    -  handler: Handler
}

abstract class Handler{
    + handle_request()
}

class Receiver1{
    + handle_request()
}

class Receiver2{
    + handle_request()
}

class Receiver3{
    + handle_request()
}

Receiver1 -up-|> Handler
Receiver2 -up-|> Handler
Receiver3 -up-|> Handler

Sender --> Handler: handler

Handler --> Handler: successor

@enduml
